// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customers": {
            "get": {
                "description": "Lista clientes com paginação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Lista clientes",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/customer.Customer"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo cliente no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Cria um novo cliente",
                "parameters": [
                    {
                        "description": "Customer data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/customer.CreateCustomerInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/customer.Customer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/customer.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/customer.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customers/document/{document}": {
            "get": {
                "description": "Busca um cliente pelo documento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Busca cliente por documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer document",
                        "name": "document",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer.Customer"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/customer.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customers/{id}": {
            "get": {
                "description": "Busca um cliente pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Busca cliente por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/customer.Customer"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/customer.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customers/{id}/status": {
            "patch": {
                "description": "Atualiza apenas o status de um cliente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Atualiza status do cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/customer.UpdateStatusInput"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/customer.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/customer.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "customer.CreateCustomerInput": {
            "type": "object",
            "properties": {
                "document": {
                    "description": "required: true\nexample: FAKE-00001",
                    "type": "string"
                },
                "income_range": {
                    "description": "example: 3000-5000",
                    "type": "string"
                },
                "name": {
                    "description": "required: true\nexample: Cliente Simulado A",
                    "type": "string"
                },
                "risk_level": {
                    "description": "required: true\nenum: LOW,MEDIUM,HIGH\nexample: LOW",
                    "type": "string"
                },
                "score": {
                    "description": "required: true\nminimum: 0\nmaximum: 1000\nexample: 742",
                    "type": "integer"
                },
                "status": {
                    "description": "required: true\nenum: ACTIVE,INACTIVE,UNDER_REVIEW\nexample: ACTIVE",
                    "type": "string"
                }
            }
        },
        "customer.Customer": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "document": {
                    "description": "Documento único do cliente.\nexample: FAKE-00001",
                    "type": "string"
                },
                "id": {
                    "description": "ID único em UUID v4.\nexample: 1f4f3c2a-8f57-4d3d-9b3e-4a2c4e2b5a1d",
                    "type": "string"
                },
                "income_range": {
                    "description": "Faixa de renda.\nexample: 3000-5000",
                    "type": "string"
                },
                "name": {
                    "description": "Nome do cliente.\nexample: Cliente Simulado A",
                    "type": "string"
                },
                "risk_level": {
                    "description": "Nível de risco.\nenum: LOW,MEDIUM,HIGH\nexample: LOW",
                    "type": "string"
                },
                "score": {
                    "description": "Score de crédito (0–1000).\nexample: 742",
                    "type": "integer"
                },
                "status": {
                    "description": "Status atual.\nenum: ACTIVE,INACTIVE,UNDER_REVIEW\nexample: ACTIVE",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "customer.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Mensagem descritiva do erro.\nexample: invalid JSON payload",
                    "type": "string"
                }
            }
        },
        "customer.UpdateStatusInput": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "required: true\nenum: ACTIVE,INACTIVE,UNDER_REVIEW\nexample: UNDER_REVIEW",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Customer Registry API",
	Description:      "Customer registration and management API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
